services:
  postgres:
    image: postgres:17
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: bfx
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
  rabbitmq:
    image: rabbitmq:4-management
    ports:
      - "5672:5672" # amqp
      - "15672:15672" # management
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
  s3:
    image: adobe/s3mock:latest
    environment:
      - COM_ADOBE_TESTING_S3MOCK_STORE_INITIAL_BUCKETS=bfx
      - COM_ADOBE_TESTING_S3MOCK_STORE_REGION=eu-central-1
      - COM_ADOBE_TESTING_S3MOCK_STORE_ROOT=/data
      - COM_ADOBE_TESTING_S3MOCK_STORE_RETAIN_FILES_ON_EXIT=true
    ports:
      - "2323:9090"
    volumes:
      - minio_data:/data

volumes:
  postgres_data:
  rabbitmq_data:
  minio_data:
